name: flutter_mailer
description: Share an email to device Email - Client supports multiple Attachments
version: 0.0.1
author: Tal Jaconson
homepage: 

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.dataxad.fluttermailer
    pluginClass: FlutterMailerPlugin

